using System;
using System.Collections.Generic;
using System.IO;
using UnityPpoRacingTrainer.Core.AiDriver.Loop;
using UnityPpoRacingTrainer.Core.AiDriver.Physics;
using UnityPpoRacingTrainer.Core.AiDriver.Training;
using UnityPpoRacingTrainer.Core.AiDriver.Training.Curriculum;
using UnityPpoRacingTrainer.Core.AiDriver.Training.Generation;
using UnityPpoRacingTrainer.Core.Terrain;
using UnityPpoRacingTrainer.Core.Terrain.Scenarios;
using UnityPpoRacingTrainer.Core.Track;
using UnityPpoRacingTrainer.Core.Track.Generation.Realistic;
using UnityPpoRacingTrainer.Core.Track.Generation.Realistic.Native;
using UnityPpoRacingTrainer.Core.Track.Loop;
using UnityPpoRacingTrainer.Core.Track.Ribbon;
using UnityPpoRacingTrainer.Core.Track.Shape;
using Unidad.Core.Grid;
using Unidad.Core.Testing;
using Unity.InferenceEngine;
using Unity.MLAgents.Policies;
using UnityEngine;

namespace UnityPpoRacingTrainer.Core.AiDriver.Policy.Scenarios
{
    /// <summary>
    /// Realistic F1-style loop generated by <see cref="RealisticTrackGenerator"/>,
    /// then driven by the trained <see cref="AiDriverAgentBehaviour"/> in
    /// <c>InferenceOnly</c> mode. Uses the AiDriverAgent_Test.prefab in
    /// <c>Resources/AiDriver/</c> (BehaviorType=InferenceOnly + ONNX assigned),
    /// so swapping the prefab's Model field swaps the policy under test.
    /// </summary>
    internal sealed class RealisticLoopInferenceScenario : DataDrivenScenario
    {
        private const int TerrainWidth = 60;
        private const int TerrainDepth = 60;
        private const int OriginX = 12;
        private const int OriginZ = 30;
        private const string TestPrefabResourcePath = "AiDriver/AiDriverAgent_Test";
        // Resources.Load path (no extension, no Resources/ prefix). The deployed
        // ONNX is at Assets/Resources/AiDriver/Policies/RacingDriver.onnx.
        private const string DefaultModelResourcePath = "AiDriver/Policies/RacingDriver";

        // -- service graph --
        private ScenarioEventBus _eventBus;
        private ScenarioGameObjectFactory _factory;
        private TerrainService _terrain;
        private TerrainMeshBuilder _terrainMeshBuilder;
        private TrackPieceCatalog _pieceCatalog;
        private TrackPieceMeshBuilder _pieceMeshBuilder;
        private List<ITrackPlacementValidator> _validators;
        private TrackPlacementService _placement;
        private TrackCollisionService _collision;
        private TrackRibbonService _ribbonService;
        private ClosedLoopService _loopService;
        private TrackQueryService _trackQuery;
        private TrackShapeCatalog _shapeCatalog;
        private ShapePreviewService _shapePreview;
        private ShapePlacementService _shapePlacement;
        private RealisticNativeCatalog _native;
        private RealisticTrackGenerator _generator;
        private CarSimulationService _carSim;
        private DriverProfileRegistry _profileRegistry;
        private AiDriverPolicyService _policyService;

        // -- presentation --
        private GameObject _terrainObject;
        private Mesh _terrainMesh;
        private Material _terrainMaterial;
        private GameObject _agentObject;
        private GameObject _carVisual;
        private AiDriverAgentBehaviour _agent;
        private RealisticLoopInferenceTickProxy _tickProxy;

        // -- runtime --
        private GenerationResult _lastResult;
        private bool _agentReady;
        // Set when an environmental precondition (missing test prefab, missing ONNX)
        // makes the scenario impossible to run. Verify turns this into a Skip.
        private string _skipReason;

        public RealisticLoopInferenceScenario() : base(new TestScenarioDefinition(
            "ai-driver-realistic-inference",
            "AI Driver — Realistic Loop + Inference (Live)",
            "Generates a realistic F1-style loop and instantiates the trained " +
            "AiDriverAgent_Test prefab (InferenceOnly + ONNX) at the lap start. " +
            "Use this to watch the policy drive on procedurally generated tracks " +
            "without a Python trainer. Same seed → identical track.",
            new[]
            {
                new ScenarioParameter("seed", "Seed", typeof(int), 1234, 0, 1_000_000),
                new ScenarioParameter("targetLengthCells", "Target Length (cells)", typeof(int), 60, 20, 200),
                new ScenarioParameter("turnDensity", "Turn Density (0..1)", typeof(float), 0.4f, 0f, 1f),
                new ScenarioParameter("beamWidth", "Beam Width", typeof(int), 16, 1, 64),
                new ScenarioParameter("attempts", "Attempts (RecipeAttempts)", typeof(int), 6, 1, 16),
                new ScenarioParameter("cameraFollow", "Camera follows car", typeof(bool), false),
            }))
        { }

        protected override void ExecuteInternal(ScenarioParameterOverrides overrides)
        {
            int seed = ResolveParam<int>(overrides, "seed");
            int targetLengthCells = ResolveParam<int>(overrides, "targetLengthCells");
            float turnDensity = ResolveParam<float>(overrides, "turnDensity");
            int beamWidth = ResolveParam<int>(overrides, "beamWidth");
            int attempts = ResolveParam<int>(overrides, "attempts");
            bool cameraFollow = ResolveParam<bool>(overrides, "cameraFollow");

            var stage = CurriculumStages.Default;

            _eventBus = new ScenarioEventBus();
            _factory = new ScenarioGameObjectFactory();

            BuildTerrain();
            BuildTrackServices();
            BuildShapeServices();
            BuildAiDriverServices();
            GenerateLoop(seed, stage, targetLengthCells, turnDensity, beamWidth, attempts);
            BuildRibbon();
            SpawnAgent();
            HookTickProxy();
            ApplyIsoCamera();
            if (cameraFollow) AttachCarFollowCamera();

            Debug.Log($"[RealLoopInfer] Ready. stage={stage.Name} seed={seed} " +
                      $"loopClosed={_loopService.IsLoopClosed} agentReady={_agentReady} " +
                      $"placed={_lastResult.PlacedPieces} length={_lastResult.TotalLength:F1}m");
        }

        protected override ScenarioVerificationResult VerifyInternal(ScenarioParameterOverrides overrides)
        {
            // Missing test prefab or ONNX are environment preconditions, not
            // regressions. Skip cleanly on a clean clone / CI; the LogWarning
            // path in SpawnAgent already explained how to fix it locally.
            if (!string.IsNullOrEmpty(_skipReason))
            {
                return ScenarioVerificationResult.Skip(_skipReason);
            }

            var checks = new List<ScenarioVerificationResult.CheckResult>
            {
                new("loop closed",
                    _loopService != null && _loopService.IsLoopClosed,
                    "ClosedLoopService did not detect a loop after generation"),
                new("agent registered",
                    _agentReady && _agent != null && _agent.IsRegistered,
                    "AiDriverAgentBehaviour did not register with the policy service"),
                new("track query active",
                    _trackQuery != null && _trackQuery.HasLoop,
                    "TrackQueryService reports no active loop"),
            };
            return new ScenarioVerificationResult(checks);
        }

        protected override void OnCleanup()
        {
            // Detach the car-follow camera so the iso view restores cleanly on
            // the next non-follow run (its OnDisable already restores the pose).
            var cam = Camera.main;
            if (cam != null)
            {
                var follow = cam.GetComponent<CarFollowCamera>();
                if (follow != null) UnityEngine.Object.DestroyImmediate(follow);
            }

            if (_tickProxy != null) _tickProxy.OnFixedUpdate = null;
            _tickProxy = null;

            if (_agent != null && _agent.gameObject != null)
            {
                UnityEngine.Object.DestroyImmediate(_agent.gameObject);
            }
            _agent = null;
            _agentReady = false;
            _skipReason = null;

            _ribbonService?.Dispose();
            _generator?.Dispose();
            _native?.Dispose();
            _carSim?.Dispose();
            _trackQuery?.Dispose();
            _loopService?.Dispose();
            _placement?.Dispose();
            _factory?.Dispose();
            _eventBus?.ClearAllSubscriptions();

            _ribbonService = null; _generator = null; _native = null;
            _carSim = null; _trackQuery = null; _loopService = null;
            _placement = null; _shapePlacement = null; _shapePreview = null;
            _shapeCatalog = null; _pieceCatalog = null;
            _factory = null; _eventBus = null;

            DestroyAny(_terrainMesh); _terrainMesh = null;
            DestroyAny(_terrainMaterial); _terrainMaterial = null;

            _carVisual = null;
            _agentObject = null;
            _terrainObject = null;
        }

        // -------------------- build --------------------

        private void BuildTerrain()
        {
            _terrain = new TerrainService(_eventBus);
            _terrain.Initialize(new TerrainBuildOptions(TerrainWidth, TerrainDepth, 0, TrackPieceConstants.CellSize));

            _terrainMeshBuilder = new TerrainMeshBuilder();
            _terrainMesh = _terrainMeshBuilder.Build(_terrain, TerrainPalette.BoneAndSlate, TerrainColorMode.Palette);
            _terrainMaterial = ResolveOpaqueMaterial("AiDriver_RealLoopInfer_TerrainMat");

            _terrainObject = _factory.CreateEmpty("[RealLoopInfer] Terrain");
            _terrainObject.transform.SetParent(SceneRoot.transform, false);

            var mf = _terrainObject.AddComponent<MeshFilter>();
            mf.sharedMesh = _terrainMesh;
            var mr = _terrainObject.AddComponent<MeshRenderer>();
            mr.sharedMaterial = _terrainMaterial;
        }

        private void BuildTrackServices()
        {
            _pieceCatalog = new TrackPieceCatalog();
            TrackPieceCatalogSeeder.Seed(_pieceCatalog);

            _pieceMeshBuilder = new TrackPieceMeshBuilder(new FlatHeightAdapter());
            _validators = new List<ITrackPlacementValidator>
            {
                new BoundsValidator(),
                new OverlapValidator(),
                new TerrainCompatibilityValidator()
            };

            _collision = new TrackCollisionService();
            _placement = new TrackPlacementService(_eventBus, _pieceCatalog, _pieceMeshBuilder,
                _validators, _terrain, _factory, TrackPalette.Default, _collision);
        }

        private void BuildShapeServices()
        {
            _shapeCatalog = new TrackShapeCatalog();
            TrackShapeCatalogSeeder.Seed(_shapeCatalog, _pieceCatalog);
            _shapePreview = new ShapePreviewService(_pieceCatalog, _validators, _terrain, _placement);
            _shapePlacement = new ShapePlacementService(_eventBus, _shapePreview, _placement);
        }

        private void BuildAiDriverServices()
        {
            _loopService = new ClosedLoopService(_eventBus, _placement, _pieceCatalog, _terrain);
            _trackQuery = new TrackQueryService(_eventBus, _loopService, _collision);
            _carSim = new CarSimulationService(_eventBus, _trackQuery, _collision);
            _profileRegistry = new DriverProfileRegistry();
            var manifests = Versions.Manifest.VersionManifestLoader.LoadAll();
            if (!manifests.TryGetValue("latest", out var latestManifest))
            {
                Debug.LogError("[RealisticLoopInferenceScenario] latest manifest missing under Assets/_Bootstrap/Configs/Versions/; using baked defaults.");
                latestManifest = new Versions.Manifest.VersionManifest();
            }
            var versionProfile = new Versions.Manifest.ManifestBackedVersionProfile(
                latestManifest,
                () => NullRewardShaper.Instance);
            _policyService = new AiDriverPolicyService(_eventBus, _carSim, _trackQuery, _loopService, _profileRegistry, versionProfile, _collision);
        }

        private void GenerateLoop(int seed, CurriculumStage stage, int targetLengthCells,
            float turnDensity, int beamWidth, int attempts)
        {
            _native = new RealisticNativeCatalog(_shapeCatalog, _pieceCatalog);
            _generator = new RealisticTrackGenerator(
                _eventBus, _placement, _shapePlacement, _loopService,
                _shapeCatalog, _pieceCatalog, _terrain, _native);

            var cfg = new RealisticTrackGenerationConfig(
                Seed: seed,
                Origin: new GridPosition(OriginX, OriginZ),
                InitialFacing: TrackDirection.East,
                Stage: stage,
                RecipeAttempts: attempts,
                TargetLengthCells: targetLengthCells,
                TurnDensity: turnDensity,
                BeamWidth: beamWidth);

            _lastResult = _generator.Generate(cfg);

            // Same fallback contract as the curriculum selector — never leave the
            // user with an open loop.
            if (!_lastResult.Success)
            {
                Debug.LogWarning($"[RealLoopInfer] realistic generation failed: stage={stage.Name} " +
                                 $"seed={seed}: {_lastResult.FailureReason} — falling back to ShapeBased");
                _placement.Clear();
                var shapeBased = new ShapeBasedLoopGenerator(_eventBus, _shapePlacement,
                    _shapeCatalog, _placement, _loopService);
                _lastResult = shapeBased.Generate(new GenerationConfig(seed,
                    new GridPosition(OriginX, OriginZ), TrackDirection.East, stage));
            }
        }

        private void BuildRibbon()
        {
            _ribbonService = new TrackRibbonService(_eventBus, _placement, _pieceCatalog,
                _terrain, _factory, TrackPalette.Default);
            _ribbonService.Rebuild();
        }

        private void SpawnAgent()
        {
            if (!_loopService.TryGetCurrentLoop(out var loop))
            {
                Debug.LogError("[RealLoopInfer] no closed loop — cannot spawn agent.");
                return;
            }

            // Single source of truth — see ClosedLoop.GetCanonicalStartPose.
            var pose = loop.GetCanonicalStartPose();
            Vector3 spawnPos = pose.position;
            float heading = loop.GetCanonicalStartHeading();

            // Same start-line + sector visualization the trainer uses.
            SectorBoundaryDebugRenderer.MountOn(SceneRoot, _loopService);

            // Instantiating the test prefab carries its BehaviorParameters
            // (Model assigned, BehaviorType=InferenceOnly) and DecisionRequester.
            // Falls back to AiDriverAgent if the test prefab is missing.
            var prefab = Resources.Load<GameObject>(TestPrefabResourcePath);
            if (prefab == null)
            {
                _skipReason =
                    $"prefab missing at Resources/{TestPrefabResourcePath}.prefab — " +
                    "duplicate AiDriverAgent.prefab and set BehaviorType=InferenceOnly + Model.";
                Debug.LogWarning("[RealLoopInfer] " + _skipReason);
                return;
            }

            // Build the GameObject INACTIVE first so we can assign the ModelAsset
            // before ML-Agents' Agent.OnEnable runs (it throws "Can't use
            // BehaviorType InferenceOnly without a model" on enable if the prefab
            // override didn't carry the reference through Instantiate).
            bool wasActive = prefab.activeSelf;
            if (wasActive) prefab.SetActive(false);
            _agentObject = UnityEngine.Object.Instantiate(prefab, spawnPos, Quaternion.identity);
            if (wasActive) prefab.SetActive(true); // restore source asset state
            _agentObject.SetActive(false);
            _agentObject.name = "[RealLoopInfer] Agent";
            _agentObject.transform.SetParent(SceneRoot.transform, false);
            _agentObject.transform.position = spawnPos;

            // Force-assign the ONNX so Agent.OnEnable doesn't throw if the prefab
            // override's m_Model fileID drifted (Sentis vs Barracuda main-asset
            // fileIDs differ; reference can deserialize null even with valid GUID).
            var behaviorParams = _agentObject.GetComponent<BehaviorParameters>();
            if (behaviorParams != null)
            {
                if (behaviorParams.Model == null)
                {
                    var model = Resources.Load<ModelAsset>(DefaultModelResourcePath);
                    if (model == null)
                    {
                        _skipReason =
                            $"Model missing at Resources/{DefaultModelResourcePath}.onnx — " +
                            "cannot run InferenceOnly. Train + copy ONNX into Resources/AiDriver/Policies/.";
                        Debug.LogWarning("[RealLoopInfer] " + _skipReason);
                        UnityEngine.Object.DestroyImmediate(_agentObject);
                        _agentObject = null;
                        return;
                    }
                    behaviorParams.Model = model;
                }
                behaviorParams.BehaviorType = BehaviorType.InferenceOnly;
            }

            _agent = _agentObject.GetComponent<AiDriverAgentBehaviour>();
            if (_agent == null)
            {
                Debug.LogError("[RealLoopInfer] spawned prefab is missing AiDriverAgentBehaviour.");
                UnityEngine.Object.DestroyImmediate(_agentObject);
                _agentObject = null;
                return;
            }
            _agent.Configure("default", spawnPos, heading);
            _agentObject.SetActive(true); // Agent.OnEnable + Initialize fire here, model is now assigned
            _agent.BindPolicy(_policyService);
            _agentReady = _agent.IsRegistered;

            // Visual cube tracks the simulated car position. Signal red so the
            // viewer can pick the agent out from terrain mesh in iso view.
            _carVisual = _factory.CreatePrimitive(PrimitiveType.Cube, "[RealLoopInfer] CarVisual",
                spawnPos + new Vector3(0f, 0.1f, 0f));
            _carVisual.transform.SetParent(SceneRoot.transform, false);
            _carVisual.transform.localScale = new Vector3(0.25f, 0.18f, 0.4f);
            var renderer = _carVisual.GetComponent<MeshRenderer>();
            if (renderer != null)
            {
                // Skip the terrain vertex-color shader for the car — the cube
                // primitive has no vertex colours so it'd render white. Pick the
                // first shader that actually honors _Color / _BaseColor.
                var mat = ResolveColoredMaterial("AiDriver_RealLoopInfer_CarMat",
                    new Color(0.92f, 0.18f, 0.18f, 1f)); // signal red
                renderer.sharedMaterial = mat;
            }
        }

        private void HookTickProxy()
        {
            var proxyGo = _factory.CreateEmpty("[RealLoopInfer] TickProxy");
            proxyGo.transform.SetParent(SceneRoot.transform, false);
            _tickProxy = proxyGo.AddComponent<RealisticLoopInferenceTickProxy>();
            _tickProxy.OnFixedUpdate = OnFixedUpdate;
            _tickProxy.OnUpdate = OnUpdate;
        }

        private void ApplyIsoCamera()
        {
            var cam = Camera.main;
            if (cam == null) return;
            float c = TrackPieceConstants.CellSize;
            var target = new Vector3(TerrainWidth * 0.5f * c, 0f, TerrainDepth * 0.5f * c);
            cam.transform.position = target + new Vector3(20f * c, 24f * c, -20f * c);
            cam.transform.LookAt(target);
        }

        private void AttachCarFollowCamera()
        {
            if (_carVisual == null) return;
            var cam = Camera.main;
            if (cam == null) return;
            // Reuse if the component is already on the camera (e.g. user toggled
            // and re-ran). OnDisable in CarFollowCamera restores the iso pose.
            var follow = cam.GetComponent<CarFollowCamera>();
            if (follow == null) follow = cam.gameObject.AddComponent<CarFollowCamera>();
            follow.Target = _carVisual.transform;
            follow.LocalOffset = new Vector3(0f, 1.4f, -2.6f);
            follow.LookAtOffset = new Vector3(0f, 0.3f, 0f);
            follow.PositionSmoothTime = 0.15f;
            follow.RotationLerpSpeed = 8f;
            follow.enabled = true;
        }

        private void OnFixedUpdate(float dt)
        {
            _carSim?.FixedTick(dt);
        }

        private void OnUpdate(float dt)
        {
            if (!_agentReady) return;
            if (!_carSim.TryGetState(_agent.CarId, out var state)) return;
            if (_carVisual == null) return;
            _carVisual.transform.position = state.Position + new Vector3(0f, 0.1f, 0f);
            _carVisual.transform.rotation = Quaternion.Euler(0f, state.Heading * Mathf.Rad2Deg, 0f);

            // Phase 2: mirror the policy's wall-feeler rays as Editor-only debug
            // lines (Scene view). Same constants the obs assembler uses, so what
            // you see is what the policy gets fed.
            if (_collision != null)
            {
                float h = state.Heading;
                float ch = Mathf.Cos(h);
                float sh = Mathf.Sin(h);
                Vector2 originXZ = new(state.Position.x, state.Position.z);
                Vector3 originW = state.Position + Vector3.up * 0.45f;
                float maxR = RacingObservationLayout.WallRayMaxMeters;
                for (int i = 0; i < RacingObservationLayout.WallRayCount; i++)
                {
                    float a = RacingObservationLayout.WallRayAnglesRad[i];
                    float ca = Mathf.Cos(a);
                    float sa = Mathf.Sin(a);
                    float dx = sh * ca + ch * sa;
                    float dz = ch * ca - sh * sa;
                    float d = _collision.RaycastWall(originXZ, new Vector2(dx, dz), maxR);
                    Vector3 endW = originW + new Vector3(dx, 0f, dz) * d;
                    float occ = 1f - Mathf.Clamp01(d / maxR);
                    Debug.DrawLine(originW, endW, Color.Lerp(Color.yellow, Color.red, occ));
                }
            }
        }

        // -------------------- helpers --------------------

        private Material ResolveOpaqueMaterial(string name)
        {
            var shader = Shader.Find("RaceConstructor/TerrainVertexColor")
                         ?? Shader.Find("Universal Render Pipeline/Lit")
                         ?? Shader.Find("Standard");
            return new Material(shader) { name = name };
        }

        // Cubes / primitives have no vertex colors, so the terrain vertex-color
        // shader renders them white. Use a shader that honors the Color/BaseColor
        // property and set both names so URP-Lit and Standard both apply.
        private Material ResolveColoredMaterial(string name, Color color)
        {
            var shader = Shader.Find("Universal Render Pipeline/Lit")
                         ?? Shader.Find("Standard")
                         ?? Shader.Find("Hidden/InternalErrorShader");
            var mat = new Material(shader) { name = name };
            mat.color = color;
            if (mat.HasProperty("_BaseColor")) mat.SetColor("_BaseColor", color);
            return mat;
        }

        private static void DestroyAny(UnityEngine.Object o)
        {
            if (o == null) return;
            if (Application.isPlaying) UnityEngine.Object.Destroy(o);
            else UnityEngine.Object.DestroyImmediate(o);
        }
    }

    /// <summary>
    /// Authored-only realistic-loop closure scenario. The shape catalog is fed
    /// exclusively by <see cref="AuthoredCardLoader"/> (the player's saved
    /// Track Editor cards) plus the four <see cref="ClosureTransitionShapes"/>
    /// — there is no <see cref="TrackShapeCatalogSeeder"/> recipe pool. The
    /// generator anchors with a 6–10 cell <c>closure:long-straight</c>, then
    /// composes authored cards for the body and closure-transition primitives
    /// (no walls / no kerbs) to bridge the closing seam. Validates that loop
    /// closure works without the previous runtime Bezier fallback.
    /// <para>Co-located with <see cref="RealisticLoopInferenceScenario"/> so
    /// Unity's auto-generated .csproj picks the type up without an editor
    /// refresh (per project memory <c>feedback_unity_new_cs_files</c>).</para>
    /// </summary>
    internal sealed class AuthoredOnlyClosureLoopScenario : DataDrivenScenario
    {
        private const int TerrainWidth = 60;
        private const int TerrainDepth = 60;
        private const int OriginX = 12;
        private const int OriginZ = 30;

        private ScenarioEventBus _eventBus;
        private ScenarioGameObjectFactory _factory;
        private TerrainService _terrain;
        private TerrainMeshBuilder _terrainMeshBuilder;
        private TrackPieceCatalog _pieceCatalog;
        private TrackPieceMeshBuilder _pieceMeshBuilder;
        private List<ITrackPlacementValidator> _validators;
        private TrackPlacementService _placement;
        private TrackCollisionService _collision;
        private TrackRibbonService _ribbonService;
        private ClosedLoopService _loopService;
        private TrackShapeCatalog _shapeCatalog;
        private ShapePreviewService _shapePreview;
        private ShapePlacementService _shapePlacement;
        private RealisticNativeCatalog _native;
        private RealisticTrackGenerator _generator;

        private GameObject _terrainObject;
        private Mesh _terrainMesh;
        private Material _terrainMaterial;

        private GenerationResult _lastResult;
        private int _authoredShapeCount;
        private int _closureShapeCount;
        private int _anchorStraightCells;

        public AuthoredOnlyClosureLoopScenario() : base(new TestScenarioDefinition(
            "ai-driver-authored-only-closure",
            "AI Driver — Authored-Only Closure (Live)",
            "Procedurally generates a closed loop using ONLY authored Track Editor " +
            "cards plus the four closure-transition primitives (rect-straight, 90° " +
            "curve, 45° curve right/left), each pinned to its bare (no-walls) " +
            "variant. The opening straight is a 6–10 cell long-anchor; the rest " +
            "of the body uses authored cards. No Bezier fallback. Pre-condition: " +
            "save at least one track via the Track Editor (F2) before running. " +
            "Same seed → same loop.",
            new[]
            {
                new ScenarioParameter("seed", "Seed", typeof(int), 1234, 0, 1_000_000),
                new ScenarioParameter("targetLengthCells", "Target Length (cells)", typeof(int), 60, 20, 200),
                new ScenarioParameter("turnDensity", "Turn Density (0..1)", typeof(float), 0.4f, 0f, 1f),
                new ScenarioParameter("beamWidth", "Beam Width", typeof(int), 16, 1, 64),
                new ScenarioParameter("attempts", "Attempts (RecipeAttempts)", typeof(int), 12, 1, 32),
                new ScenarioParameter("anchorStraightCells", "Anchor Straight (cells, 6-10)", typeof(int), 8,
                    ClosureTransitionShapes.LongStraightMinCells,
                    ClosureTransitionShapes.LongStraightMaxCells),
            }))
        { }

        protected override void ExecuteInternal(ScenarioParameterOverrides overrides)
        {
            int seed = ResolveParam<int>(overrides, "seed");
            int targetLengthCells = ResolveParam<int>(overrides, "targetLengthCells");
            float turnDensity = ResolveParam<float>(overrides, "turnDensity");
            int beamWidth = ResolveParam<int>(overrides, "beamWidth");
            int attempts = ResolveParam<int>(overrides, "attempts");
            _anchorStraightCells = ResolveParam<int>(overrides, "anchorStraightCells");

            var stage = CurriculumStages.Default;

            _eventBus = new ScenarioEventBus();
            _factory = new ScenarioGameObjectFactory();

            BuildTerrain();
            BuildTrackServices();
            BuildShapeServicesAuthoredOnly();
            BuildLoopServices();
            GenerateLoop(seed, stage, targetLengthCells, turnDensity, beamWidth, attempts);
            BuildRibbon();
            ApplyIsoCamera();

            Debug.Log($"[AuthoredClosure] stage={stage.Name} seed={seed} authored={_authoredShapeCount} " +
                      $"closure={_closureShapeCount} anchor={_anchorStraightCells} " +
                      $"loopClosed={_loopService?.IsLoopClosed} success={_lastResult.Success} " +
                      $"placed={_lastResult.PlacedPieces} length={_lastResult.TotalLength:F1}m " +
                      $"reason='{_lastResult.FailureReason}'");
        }

        protected override ScenarioVerificationResult VerifyInternal(ScenarioParameterOverrides overrides)
        {
            // Clean clone has no authored tracks on disk. Without them this scenario
            // cannot exercise its core invariant — skip rather than fail so CI stays
            // green. Local users hit the precondition message after they save a
            // track via the Track Editor (F2).
            if (_authoredShapeCount == 0)
            {
                return ScenarioVerificationResult.Skip(
                    "AuthoredCardLoader registered 0 shapes — save at least one track " +
                    "via the Track Editor (F2) before running this scenario.");
            }

            var checks = new List<ScenarioVerificationResult.CheckResult>
            {
                new("authored shapes present",
                    _authoredShapeCount > 0,
                    "AuthoredCardLoader registered 0 shapes — save at least one track via the Track Editor (F2) before running this scenario."),
                new("closure shapes registered",
                    _closureShapeCount >= 4,
                    $"ClosureTransitionShapes registered {_closureShapeCount} shapes; expected ≥4."),
                new("anchor in [6,10] range",
                    _anchorStraightCells >= ClosureTransitionShapes.LongStraightMinCells
                        && _anchorStraightCells <= ClosureTransitionShapes.LongStraightMaxCells,
                    $"Anchor straight {_anchorStraightCells} not in [{ClosureTransitionShapes.LongStraightMinCells},{ClosureTransitionShapes.LongStraightMaxCells}]."),
                new("loop closed",
                    _loopService != null && _loopService.IsLoopClosed,
                    "Generator did not close a loop using authored + closure shapes within the attempt budget."),
                new("generation success",
                    _lastResult.Success,
                    $"GenerationResult reported failure: {_lastResult.FailureReason}"),
            };
            return new ScenarioVerificationResult(checks);
        }

        protected override void OnCleanup()
        {
            _ribbonService?.Dispose();
            _generator?.Dispose();
            _native?.Dispose();
            _loopService?.Dispose();
            _placement?.Dispose();
            _factory?.Dispose();
            _eventBus?.ClearAllSubscriptions();

            _ribbonService = null; _generator = null; _native = null;
            _loopService = null; _placement = null; _shapePlacement = null;
            _shapePreview = null; _shapeCatalog = null; _pieceCatalog = null;
            _factory = null; _eventBus = null;

            DestroyAny(_terrainMesh); _terrainMesh = null;
            DestroyAny(_terrainMaterial); _terrainMaterial = null;

            _terrainObject = null;
        }

        private void BuildTerrain()
        {
            _terrain = new TerrainService(_eventBus);
            _terrain.Initialize(new TerrainBuildOptions(TerrainWidth, TerrainDepth, 0, TrackPieceConstants.CellSize));

            _terrainMeshBuilder = new TerrainMeshBuilder();
            _terrainMesh = _terrainMeshBuilder.Build(_terrain, TerrainPalette.BoneAndSlate, TerrainColorMode.Palette);
            _terrainMaterial = ResolveOpaqueMaterialAuthored("AiDriver_AuthoredClosure_TerrainMat");

            _terrainObject = _factory.CreateEmpty("[AuthoredClosure] Terrain");
            _terrainObject.transform.SetParent(SceneRoot.transform, false);

            var mf = _terrainObject.AddComponent<MeshFilter>();
            mf.sharedMesh = _terrainMesh;
            var mr = _terrainObject.AddComponent<MeshRenderer>();
            mr.sharedMaterial = _terrainMaterial;
        }

        private void BuildTrackServices()
        {
            _pieceCatalog = new TrackPieceCatalog();
            TrackPieceCatalogSeeder.Seed(_pieceCatalog);

            _pieceMeshBuilder = new TrackPieceMeshBuilder(new FlatHeightAdapter());
            _validators = new List<ITrackPlacementValidator>
            {
                new BoundsValidator(),
                new OverlapValidator(),
                new TerrainCompatibilityValidator()
            };

            _collision = new TrackCollisionService();
            _placement = new TrackPlacementService(_eventBus, _pieceCatalog, _pieceMeshBuilder,
                _validators, _terrain, _factory, TrackPalette.Default, _collision);
        }

        private void BuildShapeServicesAuthoredOnly()
        {
            _shapeCatalog = new TrackShapeCatalog();
            // Authored-only: NO TrackShapeCatalogSeeder.Seed call. Catalog is fed
            // solely by the player's saved Track Editor cards plus the closure
            // transition primitives — the generator has no recipe pool to fall
            // back to.
            _authoredShapeCount = AuthoredCardLoader.LoadAllInto(_shapeCatalog, _pieceCatalog);
            _closureShapeCount = ClosureTransitionShapes.Register(_shapeCatalog, _pieceCatalog,
                longStraightCells: _anchorStraightCells);

            _shapePreview = new ShapePreviewService(_pieceCatalog, _validators, _terrain, _placement);
            _shapePlacement = new ShapePlacementService(_eventBus, _shapePreview, _placement);
        }

        private void BuildLoopServices()
        {
            _loopService = new ClosedLoopService(_eventBus, _placement, _pieceCatalog, _terrain);
        }

        private void GenerateLoop(int seed, CurriculumStage stage, int targetLengthCells,
            float turnDensity, int beamWidth, int attempts)
        {
            _native = new RealisticNativeCatalog(_shapeCatalog, _pieceCatalog);
            _generator = new RealisticTrackGenerator(
                _eventBus, _placement, _shapePlacement, _loopService,
                _shapeCatalog, _pieceCatalog, _terrain, _native);

            int minMainStraight = ClosureTransitionShapes.LongStraightMinCells;
            var cfg = new RealisticTrackGenerationConfig(
                Seed: seed,
                Origin: new GridPosition(OriginX, OriginZ),
                InitialFacing: TrackDirection.East,
                Stage: stage,
                RecipeAttempts: attempts,
                TargetLengthCells: targetLengthCells,
                TurnDensity: turnDensity,
                BeamWidth: beamWidth,
                MinMainStraightCells: minMainStraight);

            _lastResult = _generator.Generate(cfg);

            if (!_lastResult.Success)
            {
                Debug.LogError($"[AuthoredClosure] generation failed: stage={stage.Name} " +
                               $"seed={seed} authored={_authoredShapeCount} closure={_closureShapeCount}: " +
                               $"{_lastResult.FailureReason} — no Bezier fallback. Save more authored cards " +
                               "via the Track Editor or relax the attempt budget.");
            }
        }

        private void BuildRibbon()
        {
            _ribbonService = new TrackRibbonService(_eventBus, _placement, _pieceCatalog,
                _terrain, _factory, TrackPalette.Default);
            _ribbonService.Rebuild();
        }

        private void ApplyIsoCamera()
        {
            var cam = Camera.main;
            if (cam == null) return;
            float c = TrackPieceConstants.CellSize;
            var target = new Vector3(TerrainWidth * 0.5f * c, 0f, TerrainDepth * 0.5f * c);
            cam.transform.position = target + new Vector3(20f * c, 24f * c, -20f * c);
            cam.transform.LookAt(target);
        }

        private static Material ResolveOpaqueMaterialAuthored(string name)
        {
            var shader = Shader.Find("RaceConstructor/TerrainVertexColor")
                         ?? Shader.Find("Universal Render Pipeline/Lit")
                         ?? Shader.Find("Standard");
            return new Material(shader) { name = name };
        }

        private static void DestroyAny(UnityEngine.Object o)
        {
            if (o == null) return;
            if (Application.isPlaying) UnityEngine.Object.Destroy(o);
            else UnityEngine.Object.DestroyImmediate(o);
        }
    }

#if UNITY_EDITOR
    /// <summary>
    /// Headless batch generator: runs the realistic track generator under the
    /// authored-only-closure pipeline (same wiring as
    /// <see cref="AuthoredOnlyClosureLoopScenario"/>) for N seeds and serialises
    /// each closed loop as a curriculum-replay-compatible JSON. Outputs land in
    /// <c>circuits/stage_authored_closure/</c> — a fresh folder so existing
    /// libraries (<c>stage_2/3/5</c>) stay intact. Failed seeds are skipped and
    /// counted in the final summary; existing files are left untouched so
    /// re-running fills gaps without churn.
    /// <para>Co-located with <see cref="AuthoredOnlyClosureLoopScenario"/> so the
    /// generator can reach <c>internal</c> service types in the Core asmdef
    /// (the Editor asmdef can't); MenuItem + AssetDatabase calls are gated by
    /// <c>UNITY_EDITOR</c>.</para>
    /// </summary>
    public static class AuthoredClosureCircuitLibrary
    {
        public const string OutputFolderName = "stage_authored_closure";
        public const int DefaultBatchSize = 10;
        public const int DefaultTargetLengthCells = 95;
        public const float DefaultTurnDensity = 0.4f;
        public const int DefaultBeamWidth = 16;
        public const int DefaultAttempts = 16;
        public const int DefaultAnchorStraightCells = 8;

        private const int TerrainWidth = 100;
        private const int TerrainDepth = 100;
        private const int OriginX = 50;
        private const int OriginZ = 50;

        [UnityEditor.MenuItem("Build/Authored Closure Circuit Library — Backfill Start Anchors")]
        public static void BackfillStartAnchorsMenu() => BackfillStartAnchors();

        /// <summary>
        /// Walks every <c>circuits/stage_authored_closure/*.json</c>, replays
        /// the placements through a fresh GenContext to rebuild the canonical
        /// <see cref="ClosedLoop"/> (which carries the CCW-flipped anchor
        /// order + correct <c>LapStartAnchorIndex</c>), and rewrites the JSON
        /// with the authoritative anchors + sector indices. Idempotent.
        ///
        /// Run this once after pulling the "single source of truth" fix to
        /// retrofit pre-existing library files whose START label disagrees
        /// with the simulator's spawn pose in the Python dashboard.
        /// </summary>
        public static int BackfillStartAnchors()
        {
            string outDir = Path.Combine("circuits", OutputFolderName);
            if (!Directory.Exists(outDir))
            {
                Debug.LogWarning($"[AuthoredClosureLib] backfill skipped — no {outDir} dir.");
                return 0;
            }
            var stage = CurriculumStages.Default;

            var files = Directory.GetFiles(outDir, "*.json");
            int updated = 0;
            int unchanged = 0;
            int failed = 0;
            bool cancelled = false;
            try
            {
                for (int i = 0; i < files.Length; i++)
                {
                    string path = files[i];
                    string name = Path.GetFileNameWithoutExtension(path);
                    if (UnityEditor.EditorUtility.DisplayCancelableProgressBar(
                            "Backfill Start Anchors", $"{name} ({i + 1}/{files.Length}) updated={updated} failed={failed}",
                            (float)i / Mathf.Max(1, files.Length)))
                    {
                        cancelled = true;
                        break;
                    }

                    CircuitFile rec;
                    try { rec = JsonUtility.FromJson<CircuitFile>(File.ReadAllText(path)); }
                    catch (Exception e)
                    {
                        Debug.LogWarning($"[AuthoredClosureLib] backfill read failed {name}: {e.Message}");
                        failed++;
                        continue;
                    }
                    if (rec == null || rec.Placements == null || rec.Placements.Count == 0)
                    {
                        failed++;
                        continue;
                    }

                    var ctx = BuildContext();
                    try
                    {
                        ctx.Placement.Clear();
                        bool brokenPiece = false;
                        for (int k = 0; k < rec.Placements.Count; k++)
                        {
                            var p = rec.Placements[k];
                            var r = ctx.Placement.TryPlace(
                                new TrackPieceShape(p.ShapeId),
                                new GridPosition(p.X, p.Y),
                                (TrackDirection)p.Facing);
                            if (!r.Success)
                            {
                                brokenPiece = true;
                                Debug.LogWarning($"[AuthoredClosureLib] backfill replay {name} failed at piece {k}: {r.Reason}");
                                break;
                            }
                        }
                        if (brokenPiece || !ctx.Loop.TryGetCurrentLoop(out var loop))
                        {
                            failed++;
                            continue;
                        }

                        var freshAnchors = SerializeLoopAnchors(loop);
                        var freshMicro = loop.Sectors.MicroBoundaryAnchor;
                        int[] freshMicroArr;
                        if (freshMicro != null && freshMicro.Count > 0)
                        {
                            freshMicroArr = new int[freshMicro.Count];
                            for (int s = 0; s < freshMicro.Count; s++) freshMicroArr[s] = freshMicro[s];
                        }
                        else
                        {
                            freshMicroArr = System.Array.Empty<int>();
                        }

                        bool sameAnchors = AnchorsEqual(rec.Anchors, freshAnchors);
                        bool sameStart = rec.LapStartAnchorIndex == loop.LapStartAnchorIndex;
                        bool sameMicro = IntArraysEqual(rec.MicroBoundaryAnchor, freshMicroArr);
                        if (sameAnchors && sameStart && sameMicro)
                        {
                            unchanged++;
                            continue;
                        }

                        rec.Anchors = freshAnchors;
                        rec.AnchorCount = freshAnchors.Count;
                        rec.LapStartAnchorIndex = loop.LapStartAnchorIndex;
                        rec.MicroBoundaryAnchor = freshMicroArr;
                        rec.TotalLength = loop.TotalLength;
                        // CircuitFile model lacks Walls/Kerbs — JsonUtility.ToJson
                        // would drop them on every backfill. Extract those raw JSON
                        // arrays from the existing file and re-inject after writing
                        // so they survive the round-trip. CircuitBarrierExportScenario
                        // remains the canonical (re)baker; we just refuse to wipe.
                        string originalText = File.ReadAllText(path);
                        string preservedWalls = ExtractFieldJson(originalText, "Walls");
                        string preservedKerbs = ExtractFieldJson(originalText, "Kerbs");
                        string newJson = JsonUtility.ToJson(rec, prettyPrint: true);
                        if (preservedWalls != null)
                            newJson = InjectBeforeClose(newJson, $"\"Walls\":{preservedWalls}");
                        if (preservedKerbs != null)
                            newJson = InjectBeforeClose(newJson, $"\"Kerbs\":{preservedKerbs}");
                        File.WriteAllText(path, newJson);
                        updated++;
                    }
                    catch (Exception e)
                    {
                        failed++;
                        Debug.LogWarning($"[AuthoredClosureLib] backfill threw {e.GetType().Name} on {name}: {e.Message}");
                    }
                    finally
                    {
                        ctx.Dispose();
                    }
                }
            }
            finally
            {
                UnityEditor.EditorUtility.ClearProgressBar();
            }

            string status = cancelled ? "CANCELLED " : "";
            Debug.Log($"[AuthoredClosureLib] {status}backfill dir='{outDir}' files={files.Length} updated={updated} unchanged={unchanged} failed={failed}.");
            UnityEditor.AssetDatabase.Refresh();
            return updated;
        }

        private static bool AnchorsEqual(List<CircuitFile.Anchor> a, List<CircuitFile.Anchor> b)
        {
            if (a == null && b == null) return true;
            if (a == null || b == null) return false;
            if (a.Count != b.Count) return false;
            for (int i = 0; i < a.Count; i++)
            {
                if (Mathf.Abs(a[i].X - b[i].X) > 1e-4f) return false;
                if (Mathf.Abs(a[i].Z - b[i].Z) > 1e-4f) return false;
            }
            return true;
        }

        private static bool IntArraysEqual(int[] a, int[] b)
        {
            int an = a?.Length ?? 0;
            int bn = b?.Length ?? 0;
            if (an != bn) return false;
            for (int i = 0; i < an; i++) if (a[i] != b[i]) return false;
            return true;
        }

        // Returns the raw JSON value of "<fieldName>": from the input text, or null
        // if absent. Walks bracket depth so nested arrays/objects (Walls = float[][])
        // are captured wholesale. Mirrors the strip-and-inject style used by
        // CircuitBarrierExportScenario so the two writers stay compatible.
        private static string ExtractFieldJson(string json, string fieldName)
        {
            string key = "\"" + fieldName + "\":";
            int idx = json.IndexOf(key, StringComparison.Ordinal);
            if (idx < 0) return null;
            int p = idx + key.Length;
            while (p < json.Length && char.IsWhiteSpace(json[p])) p++;
            if (p >= json.Length) return null;
            int end;
            char open = json[p];
            if (open == '[' || open == '{')
            {
                char close = open == '[' ? ']' : '}';
                int depth = 0;
                for (end = p; end < json.Length; end++)
                {
                    char c = json[end];
                    if (c == '"') { end = SkipStringLiteral(json, end); continue; }
                    if (c == open) depth++;
                    else if (c == close) { depth--; if (depth == 0) { end++; break; } }
                }
            }
            else if (open == '"')
            {
                end = SkipStringLiteral(json, p) + 1;
            }
            else
            {
                end = p;
                while (end < json.Length && ",}]".IndexOf(json[end]) < 0) end++;
            }
            return json.Substring(p, end - p);
        }

        private static int SkipStringLiteral(string json, int p)
        {
            for (int i = p + 1; i < json.Length; i++)
            {
                if (json[i] == '\\') { i++; continue; }
                if (json[i] == '"') return i;
            }
            return json.Length - 1;
        }

        // Splices "<fragment>" in just before the JSON's closing '}'. Adds the
        // separating comma only when the surrounding object isn't empty.
        private static string InjectBeforeClose(string json, string fragment)
        {
            int close = json.LastIndexOf('}');
            if (close < 0) return json;
            string head = json.Substring(0, close).TrimEnd();
            string tail = json.Substring(close);
            string sep = head.EndsWith("{", StringComparison.Ordinal) ? "" : ",";
            return head + sep + fragment + tail;
        }

        [UnityEditor.MenuItem("Build/Authored Closure Circuit Library (1)")]
        public static void GenerateMenu1() => RunBatch(1);
        [UnityEditor.MenuItem("Build/Authored Closure Circuit Library (3)")]
        public static void GenerateMenu3() => RunBatch(3);
        [UnityEditor.MenuItem("Build/Authored Closure Circuit Library (5)")]
        public static void GenerateMenu5() => RunBatch(5);
        [UnityEditor.MenuItem("Build/Authored Closure Circuit Library (10)")]
        public static void GenerateMenu10() => RunBatch(10);
        [UnityEditor.MenuItem("Build/Authored Closure Circuit Library (50)")]
        public static void GenerateMenu50() => RunBatch(50);
        [UnityEditor.MenuItem("Build/Authored Closure Circuit Library (100)")]
        public static void GenerateMenu100() => RunBatch(100);

        private static void RunBatch(int n)
        {
            // Random base seed each click + no wipe: each menu invocation
            // EXTENDS the library with fresh circuits. Existing files are
            // preserved (Generate skips File.Exists) and signature-dedup
            // catches accidental seed collisions across runs.
            // Seed range capped well below int.MaxValue so baseSeed+n never
            // overflows. Wide enough that collision with prior seeds is
            // astronomically unlikely.
            int baseSeed = new System.Random().Next(1, int.MaxValue - 1_000_000);
            int generated = Generate(n, baseSeed);
            Debug.Log($"[AuthoredClosureLib] menu run complete: {generated}/{n} circuits saved (baseSeed={baseSeed}).");
        }

        /// <summary>
        /// Generates <paramref name="batchSize"/> circuits with seeds
        /// <c>baseSeed..baseSeed+batchSize-1</c>. Returns the number of
        /// circuits successfully written. Skips already-existing files (no
        /// overwrite) so re-running fills gaps.
        /// </summary>
        public static int Generate(int batchSize, int baseSeed)
        {
            string outDir = Path.Combine("circuits", OutputFolderName);
            Directory.CreateDirectory(outDir);

            int authoredAvailable = AuthoredTrackJsonStore.ListIds().Count;
            if (authoredAvailable == 0)
            {
                Debug.LogError("[AuthoredClosureLib] no authored tracks on disk at " +
                               $"{Application.persistentDataPath}/AuthoredTracks. Save at least one " +
                               "track via the Track Editor scenario (F2) before running this menu.");
                return 0;
            }

            var stage = CurriculumStages.Default;

            int written = 0;
            int skipped = 0;
            int failed = 0;
            int rejected = 0;
            int duplicates = 0;
            bool cancelled = false;
            // Dedup signature → seed where it was first seen. Two seeds that
            // produce the same normalised placement list are treated as the
            // same circuit; later duplicates are rejected so the library
            // contains 100 distinct loops, not 100 copies of the easy oval.
            var signatureToSeed = LoadExistingSignatures(outDir);
            try
            {
                for (int i = 0; i < batchSize; i++)
                {
                    int seed = baseSeed + i;

                    // Cancelable progress bar — user clicks Cancel to bail
                    // mid-batch. Refresh frequency: every iteration. Returning
                    // true from DisplayCancelableProgressBar means the user hit
                    // Cancel; we break and report partial results.
                    string label = $"seed {seed} ({i + 1}/{batchSize}) — written={written} failed={failed} rejected={rejected}";
                    if (UnityEditor.EditorUtility.DisplayCancelableProgressBar(
                            "Authored Closure Circuit Library", label, (float)i / batchSize))
                    {
                        cancelled = true;
                        break;
                    }

                    string outPath = Path.Combine(outDir, $"circuit_{seed:0000}.json");
                    if (File.Exists(outPath))
                    {
                        skipped++;
                        continue;
                    }

                    var ctx = BuildContext();
                    try
                    {
                        var result = TryGenerateOne(ctx, seed, stage);
                        if (result.Success && ctx.Loop.IsLoopClosed
                            && ctx.Loop.TryGetCurrentLoop(out var loop))
                        {
                            // Quality gate: reject degenerate loops (oval
                            // bias, too short, too few pieces, low turn
                            // density). Then dedup: identical placement
                            // signatures across seeds collapse into one
                            // entry so the library shows 100 *distinct*
                            // loops, not 100 copies of the same oval.
                            if (!IsAcceptableCircuit(ctx, loop, result, out var rejectReason))
                            {
                                rejected++;
                                Debug.Log($"[AuthoredClosureLib] seed={seed} rejected: {rejectReason} {RenderAscii(ctx)}");
                                LogAsciiGrid(ctx, seed);
                            }
                            else
                            {
                                string signature = ComputeCircuitSignature(ctx);
                                if (signatureToSeed.TryGetValue(signature, out int firstSeen))
                                {
                                    duplicates++;
                                    Debug.Log($"[AuthoredClosureLib] seed={seed} duplicate of seed={firstSeen} (signature collision)");
                                }
                                else
                                {
                                    WriteCircuitFile(outPath, ctx, loop, seed, stage, result);
                                    signatureToSeed[signature] = seed;
                                    written++;
                                    Debug.Log($"[AuthoredClosureLib] seed={seed} ACCEPTED (pieces={result.PlacedPieces} length={loop.TotalLength:F1}m) {RenderAscii(ctx)}");
                                    LogAsciiGrid(ctx, seed);
                                }
                            }
                        }
                        else
                        {
                            failed++;
                            Debug.LogWarning($"[AuthoredClosureLib] seed={seed} failed: {result.FailureReason} {RenderAscii(ctx)}");
                            LogAsciiGrid(ctx, seed);
                        }
                    }
                    catch (Exception e)
                    {
                        failed++;
                        Debug.LogWarning($"[AuthoredClosureLib] seed={seed} threw {e.GetType().Name}: {e.Message}");
                    }
                    finally
                    {
                        ctx.Dispose();
                    }
                }
            }
            finally
            {
                UnityEditor.EditorUtility.ClearProgressBar();
            }

            string status = cancelled ? "CANCELLED " : "";
            Debug.Log($"[AuthoredClosureLib] {status}outDir='{outDir}' batch={batchSize} " +
                      $"written={written} skipped(existing)={skipped} duplicates={duplicates} " +
                      $"rejected={rejected} failed={failed} authoredCards={authoredAvailable}.");
            UnityEditor.AssetDatabase.Refresh();
            return written;
        }

        /// <summary>
        /// Quality gate. Rejects: too-short loops, too-few-pieces micro-ovals,
        /// flat aspect-ratio "straight oval" layouts (the user's complaint —
        /// long horizontal corridor + short return), and loops with too few
        /// turns to count as a real circuit. Tune the constants here if the
        /// rejection rate is too aggressive.
        /// </summary>
        /// <summary>
        /// Render an ASCII map of every cell currently in the placement
        /// occupancy. Used in batch-log output so failed/rejected/accepted
        /// circuits are visually inspectable without re-running. Capped at
        /// 60×60 cells; larger grids get truncated with a marker.
        /// </summary>
        private static string RenderAscii(GenContext ctx)
        {
            // Returns a single-line summary for the headline log; the row-by-row
            // grid is emitted separately via LogAsciiGrid so Unity Console
            // doesn't collapse the multi-line message into the first line only.
            var occ = ctx.Placement.Occupancy;
            if (occ == null || occ.Count == 0) return "(empty)";
            int minX = int.MaxValue, minY = int.MaxValue;
            int maxX = int.MinValue, maxY = int.MinValue;
            foreach (var kv in occ)
            {
                if (kv.Key.X < minX) minX = kv.Key.X;
                if (kv.Key.Y < minY) minY = kv.Key.Y;
                if (kv.Key.X > maxX) maxX = kv.Key.X;
                if (kv.Key.Y > maxY) maxY = kv.Key.Y;
            }
            int w = maxX - minX + 1;
            int h = maxY - minY + 1;
            // Distinct shape kinds — user wants 10+; emit so we can see at a glance.
            var distinct = new HashSet<string>();
            foreach (var p in ctx.Placement.Placed)
                distinct.Add(p.Shape.Id);
            return $"  bbox={w}x{h} cells={occ.Count} distinctKinds={distinct.Count}";
        }

        private static void LogAsciiGrid(GenContext ctx, int seed)
        {
            var occ = ctx.Placement.Occupancy;
            if (occ == null || occ.Count == 0) return;
            int minX = int.MaxValue, minY = int.MaxValue;
            int maxX = int.MinValue, maxY = int.MinValue;
            foreach (var kv in occ)
            {
                if (kv.Key.X < minX) minX = kv.Key.X;
                if (kv.Key.Y < minY) minY = kv.Key.Y;
                if (kv.Key.X > maxX) maxX = kv.Key.X;
                if (kv.Key.Y > maxY) maxY = kv.Key.Y;
            }
            int w = maxX - minX + 1;
            int h = maxY - minY + 1;
            if (w > 110 || h > 110) { Debug.Log($"[AsciiGrid s{seed}] (too large: {w}x{h})"); return; }
            for (int y = maxY; y >= minY; y--)
            {
                var sb = new System.Text.StringBuilder(w);
                for (int x = minX; x <= maxX; x++)
                    sb.Append(occ.ContainsKey(new GridPosition(x, y)) ? '#' : '.');
                Debug.Log($"[AsciiGrid s{seed}] {sb}");
            }
        }

        private const float MinAcceptableLengthMeters = 75f;
        private const int MinAcceptablePieces = 30;
        private const float MaxAcceptableAspectRatio = 4.5f;
        private const int MinAcceptableTurnPieces = 6;

        private static bool IsAcceptableCircuit(GenContext ctx, ClosedLoop loop,
            GenerationResult result, out string reason)
        {
            if (result.PlacedPieces < MinAcceptablePieces)
            {
                reason = $"only {result.PlacedPieces} pieces (min {MinAcceptablePieces})";
                return false;
            }
            if (loop.TotalLength < MinAcceptableLengthMeters)
            {
                reason = $"length {loop.TotalLength:F1}m below floor {MinAcceptableLengthMeters}m";
                return false;
            }

            // Aspect-ratio gate — if max(W,H) / min(W,H) > MaxAcceptable, this
            // is a "long flat oval" (the user's complaint). Compute on the
            // placement bounding box — it's tight and cheap.
            int minX = int.MaxValue, minY = int.MaxValue;
            int maxX = int.MinValue, maxY = int.MinValue;
            int curveCount = 0;
            foreach (var p in ctx.Placement.Placed)
            {
                if (p.Origin.X < minX) minX = p.Origin.X;
                if (p.Origin.Y < minY) minY = p.Origin.Y;
                if (p.Origin.X > maxX) maxX = p.Origin.X;
                if (p.Origin.Y > maxY) maxY = p.Origin.Y;
                if (ctx.PieceCatalog.TryGet(p.Shape, out var def))
                {
                    if (def.Family == TrackPieceFamily.Curve
                        || def.Family == TrackPieceFamily.DiagonalCurve)
                        curveCount++;
                }
            }
            float w = Mathf.Max(1, maxX - minX + 1);
            float h = Mathf.Max(1, maxY - minY + 1);
            float aspect = Mathf.Max(w, h) / Mathf.Min(w, h);
            if (aspect > MaxAcceptableAspectRatio)
            {
                reason = $"aspect ratio {aspect:F2} > {MaxAcceptableAspectRatio} (flat oval)";
                return false;
            }
            if (curveCount < MinAcceptableTurnPieces)
            {
                reason = $"only {curveCount} curve pieces (min {MinAcceptableTurnPieces} — straight oval)";
                return false;
            }

            reason = null;
            return true;
        }

        /// <summary>
        /// Translation-invariant signature of a closed-loop layout. Two seeds
        /// that placed the same shape ids at the same relative offsets/facings
        /// hash to the same signature → second one is a duplicate. The shift
        /// to (0,0) makes the dedup invariant under origin choice, so the
        /// generator can change its anchor cell across seeds without breaking
        /// dedup.
        /// </summary>
        private static string ComputeCircuitSignature(GenContext ctx)
        {
            int minX = int.MaxValue, minY = int.MaxValue;
            foreach (var p in ctx.Placement.Placed)
            {
                if (p.Origin.X < minX) minX = p.Origin.X;
                if (p.Origin.Y < minY) minY = p.Origin.Y;
            }
            var entries = new List<string>(ctx.Placement.Placed.Count);
            foreach (var p in ctx.Placement.Placed)
            {
                entries.Add($"{p.Shape.Id}:{p.Origin.X - minX}:{p.Origin.Y - minY}:{(int)p.Facing}");
            }
            entries.Sort(StringComparer.Ordinal);
            return string.Join("|", entries);
        }

        /// <summary>
        /// On startup, hash every existing JSON in the output folder so a
        /// re-run that already wrote 50 circuits doesn't re-generate ones
        /// that match (signature-wise) what's already on disk.
        /// </summary>
        private static Dictionary<string, int> LoadExistingSignatures(string outDir)
        {
            var dict = new Dictionary<string, int>();
            if (!Directory.Exists(outDir)) return dict;
            foreach (var f in Directory.GetFiles(outDir, "*.json"))
            {
                try
                {
                    var existing = JsonUtility.FromJson<CircuitFile>(File.ReadAllText(f));
                    if (existing?.Placements == null || existing.Placements.Count == 0) continue;
                    int minX = int.MaxValue, minY = int.MaxValue;
                    foreach (var p in existing.Placements)
                    {
                        if (p.X < minX) minX = p.X;
                        if (p.Y < minY) minY = p.Y;
                    }
                    var entries = new List<string>(existing.Placements.Count);
                    foreach (var p in existing.Placements)
                    {
                        entries.Add($"{p.ShapeId}:{p.X - minX}:{p.Y - minY}:{p.Facing}");
                    }
                    entries.Sort(StringComparer.Ordinal);
                    string sig = string.Join("|", entries);
                    if (!dict.ContainsKey(sig)) dict[sig] = existing.Seed;
                }
                catch
                {
                    // Skip unreadable / mis-shaped files; they'll be left alone.
                }
            }
            return dict;
        }

        private static GenContext BuildContext()
        {
            var ctx = new GenContext();
            ctx.EventBus = new ScenarioEventBus();
            ctx.Factory = new ScenarioGameObjectFactory();

            ctx.Terrain = new TerrainService(ctx.EventBus);
            ctx.Terrain.Initialize(new TerrainBuildOptions(TerrainWidth, TerrainDepth, 0, TrackPieceConstants.CellSize));

            ctx.PieceCatalog = new TrackPieceCatalog();
            TrackPieceCatalogSeeder.Seed(ctx.PieceCatalog);

            var meshBuilder = new TrackPieceMeshBuilder(new FlatHeightAdapter());
            var validators = new List<ITrackPlacementValidator>
            {
                new BoundsValidator(),
                new OverlapValidator(),
                new TerrainCompatibilityValidator()
            };
            ctx.Collision = new TrackCollisionService();
            ctx.Placement = new TrackPlacementService(ctx.EventBus, ctx.PieceCatalog, meshBuilder,
                validators, ctx.Terrain, ctx.Factory, TrackPalette.Default, ctx.Collision);

            ctx.ShapeCatalog = new TrackShapeCatalog();
            ctx.AuthoredCount = AuthoredCardLoader.LoadAllInto(ctx.ShapeCatalog, ctx.PieceCatalog);
            ctx.ClosureCount = ClosureTransitionShapes.Register(ctx.ShapeCatalog, ctx.PieceCatalog,
                longStraightCells: DefaultAnchorStraightCells);

            var preview = new ShapePreviewService(ctx.PieceCatalog, validators, ctx.Terrain, ctx.Placement);
            ctx.ShapePlacement = new ShapePlacementService(ctx.EventBus, preview, ctx.Placement);

            ctx.Loop = new ClosedLoopService(ctx.EventBus, ctx.Placement, ctx.PieceCatalog, ctx.Terrain);

            ctx.Native = new RealisticNativeCatalog(ctx.ShapeCatalog, ctx.PieceCatalog);
            ctx.Generator = new RealisticTrackGenerator(
                ctx.EventBus, ctx.Placement, ctx.ShapePlacement, ctx.Loop,
                ctx.ShapeCatalog, ctx.PieceCatalog, ctx.Terrain, ctx.Native);

            return ctx;
        }

        private static GenerationResult TryGenerateOne(GenContext ctx, int seed, CurriculumStage stage)
        {
            // Per-seed random cardinal facing — without this, every loop launches
            // east → all layouts elongate east-west → flat-oval bias even after
            // scoring tweaks. Hash the seed into one of {N, E, S, W} (cardinal-only
            // because the placement pipeline rejects diagonal facings).
            uint h = unchecked((uint)seed * 2654435761u);
            h ^= h >> 13; h *= 1274126177u; h ^= h >> 16;
            var facings = new[] { TrackDirection.East, TrackDirection.North, TrackDirection.West, TrackDirection.South };
            var initialFacing = facings[(int)(h % 4)];

            var cfg = new RealisticTrackGenerationConfig(
                Seed: seed,
                Origin: new GridPosition(OriginX, OriginZ),
                InitialFacing: initialFacing,
                Stage: stage,
                RecipeAttempts: DefaultAttempts,
                TargetLengthCells: DefaultTargetLengthCells,
                TurnDensity: DefaultTurnDensity,
                BeamWidth: DefaultBeamWidth,
                PerAttemptTimeoutMs: 3000,
                MaxSearchSteps: 80,
                MinMainStraightCells: 4);  // 4-cell legs → more turns, less rectangular bias
            return ctx.Generator.Generate(cfg);
        }

        private static void WriteCircuitFile(string path, GenContext ctx, ClosedLoop loop,
            int seed, CurriculumStage stage, GenerationResult result)
        {
            var placements = new List<CircuitFile.Placement>(ctx.Placement.Placed.Count);
            foreach (var p in ctx.Placement.Placed)
            {
                placements.Add(new CircuitFile.Placement
                {
                    ShapeId = p.Shape.Id,
                    X = p.Origin.X,
                    Y = p.Origin.Y,
                    Facing = (int)p.Facing,
                });
            }

            // Anchors MUST come from loop.Anchors (post-CCW-flip in
            // ClosedLoopService.BuildClosedLoop) — that is the canonical
            // sequence the indices LapStartAnchorIndex / MicroBoundaryAnchor
            // refer to. Serializing a separate TrackChainExtractor.Extract()
            // run here would drop the CCW flip and make the indices reference
            // a different order than the dashboard's polyline → start label
            // lands on the wrong anchor.
            var anchors = SerializeLoopAnchors(loop);

            // Per-piece overlay segments for closure-only shapes — the Python
            // viewer renders these in a contrasting colour so the user can
            // see exactly which arcs were generator-bridged vs authored.
            var closureSegments = ExtractClosureSegments(ctx);

            var microBoundary = loop.Sectors.MicroBoundaryAnchor;
            int[] microBoundaryArr;
            if (microBoundary != null && microBoundary.Count > 0)
            {
                microBoundaryArr = new int[microBoundary.Count];
                for (int i = 0; i < microBoundary.Count; i++) microBoundaryArr[i] = microBoundary[i];
            }
            else
            {
                microBoundaryArr = System.Array.Empty<int>();
            }

            var rec = new CircuitFile
            {
                Id = $"authored_closure_{seed:0000}",
                TotalLength = loop.TotalLength,
                AnchorCount = anchors.Count,
                AuthoredCardCount = ctx.AuthoredCount,
                ClosureCardCount = ctx.ClosureCount,
                Seed = seed,
                Placements = placements,
                Anchors = anchors,
                ClosureSegments = closureSegments,
                // Single source of truth: the indices the simulator's lap
                // counter actually uses. The Python dashboard reads these as
                // overrides (server.py _compute_sector_meta) so the START
                // label snaps to the same anchor as the car's spawn pose.
                LapStartAnchorIndex = loop.LapStartAnchorIndex,
                MicroBoundaryAnchor = microBoundaryArr,
            };
            File.WriteAllText(path, JsonUtility.ToJson(rec, prettyPrint: true));
        }

        // Serialize ClosedLoop.Anchors (already CCW-canonical) so on-disk
        // anchor order matches the index domain of LapStartAnchorIndex /
        // MicroBoundaryAnchor. The blanket [Serializable] CircuitFile.Anchor
        // shape stays the same (X, Z).
        private static List<CircuitFile.Anchor> SerializeLoopAnchors(ClosedLoop loop)
        {
            var output = new List<CircuitFile.Anchor>();
            if (loop.Anchors == null) return output;
            for (int i = 0; i < loop.Anchors.Count; i++)
            {
                var a = loop.Anchors[i];
                output.Add(new CircuitFile.Anchor
                {
                    X = a.WorldPos.x,
                    Z = a.WorldPos.z,
                });
            }
            return output;
        }

        private static List<CircuitFile.Segment> ExtractClosureSegments(GenContext ctx)
        {
            var segments = new List<CircuitFile.Segment>();
            var closureIdsRaw = ctx.Generator?.LastClosurePieceIds;
            if (closureIdsRaw == null || closureIdsRaw.Count == 0) return segments;
            var closureIds = new HashSet<TrackPieceId>(closureIdsRaw);
            try
            {
                var extractor = new TrackChainExtractor(ctx.PieceCatalog);
                foreach (var p in ctx.Placement.Placed)
                {
                    if (!closureIds.Contains(p.Id)) continue;
                    if (!ctx.PieceCatalog.TryGet(p.Shape, out var def)) continue;
                    var spine = extractor.BuildWorldSpine(def, p.Origin, p.Facing,
                        TrackPieceConstants.CellSize);
                    if (spine == null || spine.Length < 2) continue;
                    var seg = new CircuitFile.Segment
                    {
                        Anchors = new List<CircuitFile.Anchor>(spine.Length),
                    };
                    for (int i = 0; i < spine.Length; i++)
                    {
                        seg.Anchors.Add(new CircuitFile.Anchor
                        {
                            X = spine[i].WorldPos.x,
                            Z = spine[i].WorldPos.z,
                        });
                    }
                    segments.Add(seg);
                }
            }
            catch
            {
                // Decorative; if extraction fails the Python viewer still has
                // the body Anchors polyline to draw.
            }
            return segments;
        }

        private static List<CircuitFile.Anchor> ExtractAnchors(GenContext ctx)
        {
            var output = new List<CircuitFile.Anchor>();
            try
            {
                var extractor = new TrackChainExtractor(ctx.PieceCatalog);
                var chains = extractor.Extract(ctx.Placement.Placed, TrackPieceConstants.CellSize);
                if (chains == null) return output;
                // Pick the longest chain — closed loops produce one chain;
                // pathological multi-chain layouts are already filtered by
                // the generator's chainCount guard.
                int bestChain = -1, bestLen = -1;
                for (int c = 0; c < chains.Count; c++)
                {
                    var chain = chains[c];
                    if (chain == null) continue;
                    if (chain.Length > bestLen) { bestLen = chain.Length; bestChain = c; }
                }
                if (bestChain < 0) return output;
                var chosen = chains[bestChain];
                for (int i = 0; i < chosen.Length; i++)
                {
                    output.Add(new CircuitFile.Anchor
                    {
                        X = chosen[i].WorldPos.x,
                        Z = chosen[i].WorldPos.z,
                    });
                }
            }
            catch
            {
                // Anchor export is decorative for the viewer; if extraction
                // throws, fall back to placements-only — Python renders cells.
            }
            return output;
        }

        // Schema mirrors the private CircuitFile inside CurriculumGeneratorSelector
        // — JsonUtility ignores unknown fields on read, so the additive fields
        // (Seed / AuthoredCardCount / ClosureCardCount) don't break the curriculum
        // replay path if anyone wires this folder into LibraryDirFor in the future.
        [Serializable]
        public sealed class CircuitFile
        {
            public string Id;
            public float TotalLength;
            public int AnchorCount;
            public int AuthoredCardCount;
            public int ClosureCardCount;
            public int Seed;
            public List<Placement> Placements;
            // Ribbon-centerline samples in world XZ. Optional — older files
            // written before this field existed deserialize with Anchors=null
            // and the Python viewer falls back to cell-square rendering.
            // ORDER MATTERS: indexed by LapStartAnchorIndex / MicroBoundaryAnchor.
            public List<Anchor> Anchors;
            // Per-closure-piece spine overlays. Each segment is the
            // world-space spine of one piece committed by a "closure:*"
            // shape. The Python viewer draws these in a contrasting colour
            // over the body Anchors polyline.
            public List<Segment> ClosureSegments;
            // Index into Anchors for the simulator's canonical start/finish
            // line. Single source of truth for the dashboard's START label —
            // without this, server.py falls back to a Python-side longest-
            // straight heuristic whose curvature threshold disagrees with C#
            // on rectangular layouts (two long similar straights → wrong
            // pick). Legacy files without this field deserialize to 0;
            // server.py treats 0 as "no override" via _compute_sector_meta's
            // bounds check.
            public int LapStartAnchorIndex;
            // K=9 anchor indices marking micro-sector boundaries, in lap
            // traversal order with sector 0 at LapStartAnchorIndex. Empty/null
            // for legacy files; server.py falls back to evenly-spaced sectors.
            public int[] MicroBoundaryAnchor;

            [Serializable]
            public sealed class Placement
            {
                public string ShapeId;
                public int X;
                public int Y;
                public int Facing;
            }

            [Serializable]
            public sealed class Anchor
            {
                public float X;
                public float Z;
            }

            [Serializable]
            public sealed class Segment
            {
                public List<Anchor> Anchors;
            }
        }

        private sealed class GenContext : IDisposable
        {
            public ScenarioEventBus EventBus;
            public ScenarioGameObjectFactory Factory;
            public TerrainService Terrain;
            public TrackPieceCatalog PieceCatalog;
            public TrackCollisionService Collision;
            public TrackPlacementService Placement;
            public TrackShapeCatalog ShapeCatalog;
            public ShapePlacementService ShapePlacement;
            public ClosedLoopService Loop;
            public RealisticNativeCatalog Native;
            public RealisticTrackGenerator Generator;
            public int AuthoredCount;
            public int ClosureCount;

            public void Dispose()
            {
                Generator?.Dispose();
                Native?.Dispose();
                Loop?.Dispose();
                Placement?.Dispose();
                Factory?.Dispose();
                EventBus?.ClearAllSubscriptions();
            }
        }
    }
#endif
}
